<trajectory>
<configuration>
<group dof="1" interpolation="" name="deltatime" offset="6"></group>
<group dof="3" interpolation="linear" name="affine_velocities PR2 11" offset="3"></group>
<group dof="3" interpolation="quadratic" name="affine_transform PR2 11" offset="0"></group>
<group dof="1" interpolation="next" name="iswaypoint" offset="7"></group>
</configuration>
<data count="2"> </data>
</trajectory>